apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: influenzanet
  name: user-management-service
  labels:
    app: user-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
      - name: user-management-service
        image: influenzanet/user-management-service:0.1.0
        env:
        - name: TOKEN_EXPIRATION_MIN
          value: "720"
        - name: TOKEN_MINIMUM_AGE_MIN
          value: "2"
        - name: DB_CONNECTION_STR
          valueFrom:
            secretKeyRef:
              name: mongodb-atlas
              key: connectionStr
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-atlas
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-atlas
              key: password
        - name: JWT_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: jwtSecret
        ports:
        - containerPort: 3200
        resources:
          requests:
            cpu: 40m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

