apiVersion: v1
kind: ConfigMap
metadata:
  name: email-server-config
  namespace: default
data:
  config.yaml: |
    namespaces:
      - default
    labels:
      - "app"
      - "owner"   