apiVersion: v1
kind: Service
metadata:
  name: management-api-service
  namespace: case
spec:
  type: ClusterIP
  clusterIP: 10.96.0.13
  selector:
    app: management-api
  ports:
  - name: grpc
    protocol: TCP
    port: 3232
    targetPort: 3232