apiVersion: v1
kind: Service
metadata:
  name: mongo-atlas-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: mongo
    role: mongo
  ports:
  - name: grpc
    protocol: TCP
    port: 27017
    targetPort: 27017