# Default values for influenzanet-2.0.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: case

# Replace this with the domain name for Influenzanet Application
domain: example.com
participantApiPath: "/api"
managementApiPath: "/admin"


# TLS Certificate Issuer Section
clusterIssuer : "letsencrypt-prod-site"
acmeServer: https://acme-v02.api.letsencrypt.org/directory
connectedEmail: sajeeth.sadananda@isi.it

# Secrets Configuration Section
jwtKey: ""
mongoUsername: "admin"
mongoPassword: "abc123"
mongoConnectionPrefix: ""
googleRecaptchaKey: "<insert-base64-key-here>"

# Persistant Storage Section
storageClass: standard
accessModes:
  - ReadWriteOnce
storageRequested: 50Gi

# Email service configuration
## Regular Email Server
smtpServers: |
  from: "username@email.com"
  sender: username@email.com
  replyTo:
    - username@email.com
  servers:
    - host: smtp.gmail.com
      port: 465
      connections: 2
      sendTimeout: 5
      auth:
        user: username@email.com
        password: "password" 

## High Priority email server
prioSmtpServers: |
  from: "username@email.com"
  sender: username@email.com
  replyTo:
    - username@email.com
  servers:
    - host: smtp.gmail.com
      port: 465
      connections: 2
      sendTimeout: 5
      auth:
        user: username@email.com
        password: "password" 

# Deployment and Service configurations for each micro-service.
## Add to this list to deploy additional micro-services
microservices:
  # EMAIL CLIENT
  email-client:
    deployment:
      name: email-client
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: email-client
        template:
          metadata:
            labels:
              app: email-client
          spec:
            containers:
            - name: email-client
              image: sajeeth1009/email-client-service-image:v0.9.1
              imagePullPolicy: Always
              env:
              - name: EMAIL_CLIENT_SERVICE_LISTEN_PORT
                value: "5005"
              - name: MESSAGING_CONFIG_FOLDER
                value: "/config"
              volumeMounts:
              - name: config-volume
                mountPath: /config/
              ports:
              - containerPort: 5005
                protocol: TCP
              - containerPort: 465
                name: smtpssl
                protocol: TCP
              - containerPort: 587
                name: smtpauth
                protocol: TCP
              resources:
                requests:
                  cpu: 30m
                  memory: 150Mi
                limits:
                  cpu: 100m
                  memory: 300Mi
            volumes:
            - name: config-volume
              configMap:
                name: email-server-config
    service:
      name: email-client-service
      spec:
        type: NodePort
        selector:
          app: email-client
        ports:
        - name: grpc
          port: 5005
          protocol: TCP
          targetPort: 5005
        - name: smtpssl-svc
          port: 465
          protocol: TCP
          targetPort: 465
        - name: smtpauth-svc
          port: 587
          protocol: TCP
          targetPort: 587