apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mailgun
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: site-tls-web
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: mailgun-webhook-service
                port:
                  number: 8080
            path: {{ .Values.endpoint }}