apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-mailgun
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: site-tls-web
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: mailgun-webhook-service
              servicePort: 8080
            path: {{ .Values.endpoint }}