apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-maintenance
  namespace: {{ .Values.namespace }}
  annotations:
{{- if not (eq .Values.issuerType "none") }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
{{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |

      location ~ ^/(?!.well-known/acme-challenge/) {
        if ($http_user_agent != "{{ .Values.allowAgent}}"){
          return 503;
        }
      }

      error_page 503 = @errorpage;

      location @errorpage {
        proxy_set_header X-Code $status;
        proxy_pass http://maintenance-service.{{ .Values.namespace }}.svc.cluster.local:3100;
      }
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: site-tls-web
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: maintenance-service
                port:
                  number: 3100
            path: /
            pathType: ImplementationSpecific