apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: case-ingress-web
  namespace: case
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: case.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-client-service
                port:
                  number: 3100