apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress
  namespace: case
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: participant-api-service
              servicePort: 3231
          - path: /admin(/|$)(.*)
            backend:
              serviceName: management-api-service
              servicePort: 3232
