apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress
  namespace: case
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod-site"
spec:
  tls:
  - hosts:
    - case.com
    secretName: site-tls
  rules:
    - host: case.com
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: participant-api-service
              servicePort: 3231
          - path: /admin(/|$)(.*)
            backend:
              serviceName: management-api-service
              servicePort: 3232