apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: case-ingress
  namespace: case
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: case.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: participant-api-service
                port:
                  number: 3231
          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: management-api-service
                port:
                  number: 3232