apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress-web
  namespace: case
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod-site"
spec:
  tls:
  - hosts:
    - case.com
    secretName: site-tls
  rules:
    - host: case.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web-client-service
              servicePort: 3100
    - host: case.com
      http:
        paths:
          - path: /home
            backend:
              serviceName: web-client-service
              servicePort: 3100