apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress-web
  namespace: case
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: web-client-service
              servicePort: 3100
          - path: /home
            backend:
              serviceName: web-client-service
              servicePort: 3100
