{{- range $key, $value := .Values.microservices }}
  {{- range $deployment := $value.deployment }}
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ $deployment.name }}
    namespace: {{ .Values.namespace }}
    labels:
      app: email-client
  spec: {{ $deployment.spec }}
  ---
  {{- end }}

  {{- range $service := $value.service }}
  apiVersion: v1
  kind: Service
  metadata:
    name: {{ $service.name }}
    namespace: {{ .Values.namespace }}
  spec: {{ $service.spec }}
  ---
  {{- end }}
{{- end }}