apiVersion: v1
kind: Service
metadata:
  name: email-client-service
  namespace: case
spec:
  type: NodePort
  selector:
    app: email-client
  ports:
  - name: grpc
    port: 5005
    protocol: TCP
    targetPort: 5005
  - name: smtpssl-svc
    port: 465
    protocol: TCP
    targetPort: 465
  - name: smtpauth-svc
    port: 587
    protocol: TCP
    targetPort: 587
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: logging
  ports:
  - name: grpc
    protocol: TCP
    port: 5006
    targetPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: management-api-service
  namespace: case
spec:
  type: NodePort
  selector:
    app: management-api
  ports:
  - name: grpc
    protocol: TCP
    port: 3232
    targetPort: 3232
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-scheduler-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: message-scheduler
  ports:
  - name: grpc
    protocol: TCP
    port: 5009
    targetPort: 5009
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: messaging
  ports:
  - name: grpc
    protocol: TCP
    port: 5004
    targetPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-atlas-service
  namespace: case
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: participant-api-service
  namespace: case
spec:
  type: NodePort
  selector:
    app: participant-api
  ports:
  - name: grpc
    protocol: TCP
    port: 3231
    targetPort: 3231
---
apiVersion: v1
kind: Service
metadata:
  namespace: case
  name: study-service
spec:
  type: ClusterIP
  selector:
    app: study
  ports:
  - name: grpc
    protocol: TCP
    port: 5003
    targetPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: user-management
  ports:
  - name: grpc
    protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-service
  namespace: case
spec:
  type: NodePort
  selector:
    app: web-client
  ports:
  - port: 3100
    targetPort: 80
