{{ if not (eq .Values.issuerType "none") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.clusterIssuer }}"
spec:
{{- if eq .Values.issuerType "acme" }}
  acme:
    server: "{{ .Values.acmeServer }}"
    email: {{ .Values.connectedEmail }}
    privateKeySecretRef:
      name: "{{ .Values.clusterIssuer }}"
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end -}}
{{- if eq .Values.issuerType "ca" }}
  ca:
    secretName: "{{ .Values.CAIssuerSecretName }}"
{{ end }}
---
{{ end }}
apiVersion: v1    
kind: Secret
metadata:
    name: jwt-collection
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    jwt-key: "{{ required "jwt key cannot be empty" .Values.jwtKey }}"
---
apiVersion: v1    
kind: Secret
metadata:
    name: case-mongodb-atlas
    namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
    username: {{ quote .Values.mongoUsername }}
    password: {{ quote .Values.mongoPassword }}
    connectionPrefix: {{ quote .Values.mongoConnectionPrefix }}
{{ if eq $.Values.useRecaptcha true }}
---
apiVersion: v1    
kind: Secret
metadata:
    name: recaptcha-collection
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    recaptchaKey: "{{ required "Recaptcha Key is required if recaptcha is activated" .Values.googleRecaptchaKey }}"
{{ end }}
---
apiVersion: v1    
kind: Secret
metadata:
    name: study-global-secret
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    secret: {{ .Values.studyGlobalSecret }}